### ISSUE TITLE
switch ftp client?

### ISSUE THREAD

**Issue by jimmywarting** [TooTallNate/node-get-uri#16]
node-ftp seems very outdated... no update for 4-5 years
how about switching client to something new? like basic-ftp or something else?

**Comment by TooTallNate** [comment]
Seems like a good idea. However, `basic-ftp` requires Node 8 and I would like to maintain Node 6 support at this time.

**Comment by pem-imre** [comment]
Is there a reason to use the n8.io url as a link for the ftpd dependency? ftpd is available from npmjs.org. I ask this because I want to keep the whitelisted domains at minimum in my build environment. I see it was changed at [this](https://github.com/TooTallNate/node-get-uri/commit/76f901a483df06ef1d9554b3146a10ec2155498d) commit.
